version: "3"

services:
  api:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - 80:80

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-ugma-today-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ugma_today

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  postgres-ugma-today-volume: {}
