version: "3"

services: 
    api:
        build: .
        ports: 
            -   80:80
        volumes: 
            -   .:/app
        working_dir: /app
        command: ["./manage.py", "runserver", "0:80"]