version: "3"

services: 
    api:
        build: .
        ports: 
            - 80:80
        volumes: 
            - .:/app
        working_dir: /app
        command: ["./manage.py", "runserver", "0:80"]
    db:
        image: postgres
        expose:
            - 5432
        environment: 
            POSTGRES_DB: ugma-today
            POSTGRES_PASSWORD: secret