version: "3"

services: 
  api:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    depends_on: 
      - postgres
    ports: 
      - 80:80

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-ugma-today-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ugma_today
                
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 4000:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ugma_today
      PGADMIN_DEFAULT_PASSWORD: secret

volumes:
  postgres-ugma-today-volume: {}
