image: registry.gitlab.com/ugma-today/ugma-today-api:latest

services:
  - postgres:latest

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: ugma_today

before_script:
- cp .env.testing .env
- php artisan key:generate
- php artisan route:clear
- php artisan config:clear
- php artisan migrate:fresh

test:app:
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never