image: php:latest 

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

services:
  - postgres:latest
  - mailhog/mailhog:latest
  - docker:dind

cache:
  paths:
    - vendor/

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: ugma_today

buid-image:
  image: docker
  type: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build --pull -t registry.gitlab.com/ugma-today/ugma-today-api
    - docker push registry.gitlab.com/ugma-today/ugma-today-api

test:
  image: php:latest
  type: test
  before_script:
    - apt-get update -yqq
    - apt-get install gnupg -yqq
    - apt-get install libpq-dev libxml2-dev curl libonig-dev libzip-dev -yqq
    - docker-php-ext-install bcmath pdo_pgsql xml pgsql intl zip opcache
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - cp .env.testing .env
    - php artisan key:generate
    - php artisan route:clear
    - php artisan config:clear
    - php artisan migrate:fresh
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never -d memory_limit=-1

staging:
    type: deploy
    image: ruby:latest
    before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
    script:
      - dpl --provider=heroku --app=$STAGING --api-key=$HEROKU_API_KEY
    only:
      - master